/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: xenadus (https://sketchfab.com/xenadus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
Title: React logo
*/

import { Float, useGLTF } from '@react-three/drei';
import * as THREE from 'three';

export function ReactLogoD(props) {
  const { nodes } = useGLTF('public/models/react.glb');

  return (
    <Float speed={5} floatIntensity={1.5}>
      <group {...props} scale={0.3} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['React-Logo_Material002_0'].geometry}
          material={new THREE.MeshBasicMaterial({ map: new THREE.TextureLoader().load('/public/textures/rings.png') })}
          position={[0, 0.079, 0.181]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.392, 0.392, 0.527]}
        />
      </group>
    </Float>
  );
}

useGLTF.preload('/react.glb');
